### ISSUE TITLE
ad block plus acts pretty unsocial

### ISSUE THREAD

**Issue by AiyionPrime** [CloudBans/web#1]
I assume you've been watching your build result using chrome or chromium.
While that leads to a nice and clean result, I'd like you to take a look at it using firefox or IE (which should fuck up, too).
The three social Icons just won't show up.
I guess and haven't verified, it's because you use a cdn and Firefox prevents cors stuff.
Maybe this helps you:
http://wpvkp.com/font-awesome-doesnt-display-in-firefox-maxcdn/
Have a nice day.

**Comment by maxikg** [comment]
Thank you for your contribution!

The webserver will now submit a CORS header. However, I wasn't able to reproduce the error by myself with the installed browsers (Chrome 48, Firefox 41, IE 11, IE 13/Edge). Can you please have a second look at it?

Have a nice day too and greetings,
  Max

**Comment by AiyionPrime** [comment]
After the cors-fix did not help me,
i killed every addon - im sorry, didnt thought about that before - ad block plus seems to have a filter "##.social-list" which hides all elements called that way.
abp does not give obvious hints About this blocking and is pretty widely used.
So while disabling it on your page solved it, you may want to condsider a diiferent name than social-list.
After some diiging I'd advise not to use any of these brackets on your page:
https://easylist-downloads.adblockplus.org/fanboy-social.txt

**Comment by maxikg** [comment]
I've refactored the class' name to `icon-list` in a3fc7b712c34fa45f82e9bebfeb143700c5ca2a0. Did it resolved the issue?

**Comment by AiyionPrime** [comment]
Sorry, been sick the last days;
haven't spent that much time coding or watching github.
The issue is resolved for the github icon, while the other two are still playing hide and seek with adblock users.
I'm going to write a code for doing this job...
apparently the filters now are ##a[title="Facebook"] ##a[title="Twitter"]
So changing the title tags to something else should do the trick.

**Comment by maxikg** [comment]
Get well soon. :)

Additionally to the both filters you've found I've also discovered `##.fa-facebook`, `##.fa-twitter`, class selectors for Font Awesome, the icon set we're using. I've just uploaded a (hopefully last) workaround with c4c2104e6ce9ad56fba1086015a37563b21c4104.

**Comment by AiyionPrime** [comment]
I'm seeing all 4 social buttons now.
Well, just kidding. Nice work, gonna close this.
